#!/bin/sh

if ! command -v adb >/dev/null 2>&1; then
    echo "adb is not installed"
    exit 1
fi

device=$(adb devices | sed -n "2 p" | cut -c 1-8)
adb -s "$device" install build/bullets-vs-bullets.apk
